### ISSUE TITLE
compiling snowcrash on windows without VS

### ISSUE THREAD

**Issue by ducin** [apiaryio/snowcrash#303]
I found in [wiki](https://github.com/apiaryio/snowcrash/wiki/Building-on-Windows) that Visual Studio 2012 or above is required to compile snowcrash on windows. Is it possible anyhow to do this without VS2012+? It's a great shame that such great library (in terms of entire api blueprint stack) relies on an IDE coming from a very specific vendor...

I need to run API blueprint stack without having python installed. The solution I'm looking for is compiling snowcrash.exe/snowcrash.dll locally on windows and using it within API blueprint tools (as stated in this [twitter thread](https://twitter.com/tomasz_ducin/status/570365954200178690)).

**Comment by tkoomzaaskz** [comment]
According to the twitter thread, I took a look at https://ci.appveyor.com/project/Apiary/snowcrash/branch/master. I am not familiar with appveyor, anyway I looked at its configuration file https://github.com/apiaryio/snowcrash/blob/master/appveyor.yml and I'm stuck, This is the build part I'm interested in:

    build_script:
      - git submodule update --init --recursive
      - vcbuild.bat MSVC2013

I need some support. I've got following questions:
* what is `vcbuild.bat MSVC2013`? MS = MicroSoft, VC = Visual C++. SO it is VIsual Studio afterall, isn't it? Am I able to compile snowcrash **without** visual studio?
* what are the dependencies (software that has to be installed on windows)?

**Comment by Almad** [comment]
@tkoomzaaskz `vcbuild.bat` is [a script in the repo](https://github.com/apiaryio/snowcrash/blob/master/vcbuild.bat).

I kinda agree depending on visual studio is a bit unfortunate, and I'd like to hear what do you think are good alternative compilers available for Windows that we should use.

//cc @XVincentX as our local Windows expert :)

**Comment by XVincentX** [comment]
To be clear, Visual Studio is not a required dependency. The one required is just the [Microsoft Windows SDK](https://msdn.microsoft.com/en-us/windows/desktop/bg162891.aspx) **and** a compiler (that you can choose), obviously.

The thing is that 
> The Windows SDK no longer ships with a complete command-line build environment. You must install a compiler and build environment separately.

While your first thought could be: "WTF", it definitely makes sense. Once you have the SDK, you can use it with Microsoft C++ Compiler, [Intel's one](https://software.intel.com/en-us/c-compilers), [Digital Mars](http://www.digitalmars.com/download/dmcpp.html), [Pelles C](http://www.smorgasbordet.com/pellesc/)

Using Microsoft Visual C++ compiler today means install Visual Studio.

In my opinion, apart Intel's compilers, Microsoft Visual C++ is the best and most adopted one and the other ones simply cannot compete with it (at least on Windows) in terms of generated code, optimizations, build system and a lot of other stuff around.

For this reason, I cannot get the reason for **shame**. It is a development dependency and I think 90% of Windows developers have got Visual Studio installed (just like XCode on Mac, I suppose).

[Visual Studio is free](https://www.visualstudio.com/en-us/products/free-developer-offers-vs.aspx), and it can be installed with a [single command](https://chocolatey.org/packages/VisualStudioCommunity2013).

We can eventually argue **why** require the IDE and not ship the compiler itself as a standalone package. I am going to ping some persons since I know that this is going to be changed with next Windows SDK version.

**Comment by zdne** [comment]
Thanks for clear explanation @XVincentX !

**Comment by kylef** [comment]
Since the original question was asked, a lot has changed in the parser toolchain. `Drafter` has replaced `Snowcrash`, at least for most uses. We have also made available a pure javascript version of drafter which can be an option if installing a C++ compiler is not possible. Obviously you will get much better performance if you install Drafter C++, but you can use Drafter directly from JavaScript if desired.

You can also use the `fury` command line tool that offers a command line interface similar to the one in Drafter (and used to be in Snowcrash) which can be installed without Python and a compiler via Node.

- Fury CLI Tool: https://github.com/apiaryio/fury-cli
- Drafter JS: https://github.com/apiaryio/drafter-npm
- Drafter C++: https://github.com/apiaryio/drafter

**Comment by XVincentX** [comment]
For the record - Microsoft is again providing build tools without any IDE

http://landinghub.visualstudio.com/visual-cpp-build-tools
